version: '3'

networks:
  crud:

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${MYSQL_HOST_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${BACKEND_DATA}/express-mysql:/var/lib/mysql
    networks:
      - crud

  phpmyadmin:
    image: phpmyadmin
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - crud

  vue:
    image: node:${VUE_NODE_VERSION}
    command: "bash ./setup.sh"
    working_dir: /usr/src/app
    ports:
      - ${VUE_HOST_PORT}:8080
    volumes:
    - ${FRONTEND_PATH}:/usr/src/app
    networks:
      - crud

  express:
    image: node:${EXPRESS_NODE_VERSION}
    command: "bash ./setup.sh"
    working_dir: /usr/src/app
    env_file: ${BACKEND_PATH}/.env
    depends_on:
      - mysql
    volumes:
    - ${BACKEND_PATH}:/usr/src/app
    ports:
      - ${EXPRESS_HOST_PORT}:3000
    networks:
      - crud