version: '3'

networks:
  crud:

services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    container_name: crud-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ~/.docker-database/express-mysql:/var/lib/mysql
    networks:
      - crud

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: crud-phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    depends_on:
      - mysql
    networks:
      - crud

  vue:
    build:
      context: .
      dockerfile: frontend/vue.Dockerfile
    container_name: crud-vue
    ports:
      - 80:8080
    volumes:
    - ./frontend:/usr/src/app
    networks:
      - crud

  express:
    build:
      context: .
      dockerfile: backend/express.Dockerfile
    container_name: crud-express
    depends_on:
      - mysql
    volumes:
    - ./backend:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - crud